server:
   port: 8087
logging:
   level:
      org:
         springframework:
            web: DEBUG
spring:
   application:
      name: spring-boot-mvc
      
brave:
   kafka:
      bootstrap-servers: PLAINTEXT://10.1.240.213:9093
      topic: zipkin
   sampler:
      probability: 1.0

      
      
      